### ISSUE TITLE
Inconsistent Ensembl Release Versions in README

### ISSUE THREAD

**Issue by Wanyang-AH** [ysbioinfo/NeoSV#3]
Hello,

I noticed a small inconsistency in the README regarding the recommended Ensembl release versions for `hg38`.

- In the **Usage - Reference file** section, it suggests using release **96** for `hg38`.
- However, in the **Run** section under "detailed description for each parameter," it mentions release **95** for `hg38`.

To avoid confusion, it might be helpful to unify both sections to consistently recommend either release **95** or **96**.

Thanks for your attention to this!

Best regards,

**Comment by ysbioinfo** [comment]
Hi Wanyang,
Thanks for pointing this out. I unified both of them to 96.
Actually 96 is the newest version for GRCh38 at the time of our publication, but now it has already been upgraded to >105. You can try those newer versions supported by Pyensembl.

Best
Yang
